apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-board
  namespace: notice-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notice-board
  template:
    metadata:
      labels:
        app: notice-board
    spec:
      containers:
        - name: notice-board
          image: AWS_ECR_URI
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
